query getCategories {
  categories {
    data {
      id
      attributes {
        name
        image {
          data {
            attributes {
              url
            }
          }
        }
        products {
          data {
            id
            attributes {
              images {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
